/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * Innoscripta News Aggregator BFF
 * Contract-first BFF that normalizes NewsAPI, The Guardian, and NYT articles.
 * OpenAPI spec version: 1.0.0
 */
import type { ProviderId } from './providerId';

export interface SourceStatus {
  provider: ProviderId;
  ok: boolean;
  /** @nullable */
  error: string | null;
}
